"""
schema.py — Single source of truth for all 88 column headers and key mappings.

Headers are copied character-for-character from the prototype Excel file,
preserving newlines, typos, and trailing spaces.
"""

from typing import NamedTuple


class ColumnDef(NamedTuple):
    key: str             # Internal snake_case name
    header: str          # Exact prototype Excel header
    group: str           # Logical field group
    extraction_hint: str # One-line hint for the LLM prompt


COLUMNS: list[ColumnDef] = [
    # ── DEMOGRAPHICS (cols 1-7) ──
    ColumnDef("dob",
              'Demographics: \nDOB(a)',
              "demographics",
              "Date of birth in DD/MM/YYYY format"),
    ColumnDef("initials",
              'Demographics: Initials(b)',
              "demographics",
              "Patient initials — first letter of first name + first letter of last name"),
    ColumnDef("mrn",
              'Demographics: MRN(c)',
              "demographics",
              "Hospital Number / Medical Record Number (numeric)"),
    ColumnDef("nhs_number",
              'Demographics: \nNHS number(d)',
              "demographics",
              "NHS Number — 10-digit identifier"),
    ColumnDef("gender",
              'Demographics: \nGender(e)',
              "demographics",
              '"Male" or "Female"'),
    ColumnDef("previous_cancer",
              'Demographics:\nPrevious cancer \n(y, n) \nif yes, where(f)',
              "demographics",
              '"Yes" or "No" — only for cancers OTHER than the current colorectal diagnosis. If clinical text mentions a prior cancer (e.g. lymphoma, breast, prostate, head and neck), answer "Yes". If no mention of any prior cancer, answer "No".'),
    ColumnDef("previous_cancer_site",
              'Demographics: \nState site of previous cancer(f)',
              "demographics",
              'Site of previous cancer (e.g. "lymphoma", "breast", "prostate"). "N/A" if previous_cancer is "No"'),

    # ── ENDOSCOPY (cols 8-10) ──
    ColumnDef("endoscopy_date",
              'Endoscopy: date(f)',
              "endoscopy",
              'Date of colonoscopy/flexi sig/sigmoidoscopy (DD/MM/YYYY). If endoscopy was done but date not stated, return "Missing"'),
    ColumnDef("endoscopy_type",
              'Endosopy type: flexi sig, incomplete colonoscopy, colonoscopy complete - if gets to ileocecal valve(f) ',
              "endoscopy",
              'Classify as: "Colonoscopy complete", "incomplete colonoscopy", or "flexi sig"'),
    ColumnDef("endoscopy_findings",
              'Endoscopy: Findings(f)',
              "endoscopy",
              "What was found during endoscopy — quote the findings text"),

    # ── HISTOLOGY (cols 11-13) ──
    ColumnDef("biopsy_result",
              'Histology: Biopsy result(g)',
              "histology",
              "Histological diagnosis from biopsy or Diagnosis field (e.g. adenocarcinoma, adenoma, dysplasia)"),
    ColumnDef("biopsy_date",
              'Histology: Biopsy date(g)',
              "histology",
              'Date of biopsy (DD/MM/YYYY). If biopsy was taken during a dated endoscopy, use that date. If not stated, return "Missing"'),
    ColumnDef("mmr_status",
              'Histology: \nMMR status(g/h)',
              "histology",
              '"Deficient" or "Proficient" — only if explicitly stated'),

    # ── BASELINE MRI (cols 14-19) ──
    ColumnDef("baseline_mri_date",
              'Baseline MRI: date(h)',
              "baseline_mri",
              "Date of MRI pelvis/rectum/liver (DD/MM/YYYY)"),
    ColumnDef("baseline_mri_mrT",
              'Baseline MRI: mrT(h)',
              "baseline_mri",
              'T staging from MRI — just the value e.g. "3b", "2", "4a"'),
    ColumnDef("baseline_mri_mrN",
              'Baseline MRI: mrN(h)',
              "baseline_mri",
              'N staging from MRI — just the value e.g. "0", "1", "1c"'),
    ColumnDef("baseline_mri_mrEMVI",
              'Baseline MRI: mrEMVI(h)',
              "baseline_mri",
              'EMVI status from MRI — "positive" or "negative"'),
    ColumnDef("baseline_mri_mrCRM",
              'Baseline MRI: mrCRM(h)',
              "baseline_mri",
              'CRM status from MRI — "clear", "involved", "threatened", or "unsafe"'),
    ColumnDef("baseline_mri_mrPSW",
              'Baseline MRI: mrPSW(h)',
              "baseline_mri",
              'PSW status from MRI — "clear" or "unsafe"'),

    # ── BASELINE CT (cols 20-26) ──
    ColumnDef("baseline_ct_date",
              'Baseline CT: Date(h)',
              "baseline_ct",
              "Date of CT TAP/abdomen/pelvis/colonography (DD/MM/YYYY). Exclude PET-CT."),
    ColumnDef("baseline_ct_T",
              'Baseline CT: T(h)',
              "baseline_ct",
              'T staging from CT — just the value e.g. "2", "3"'),
    ColumnDef("baseline_ct_N",
              'Baseline CT: N(h)',
              "baseline_ct",
              'N staging from CT — just the value e.g. "0", "1"'),
    ColumnDef("baseline_ct_EMVI",
              'Baseline CT: EMVI(h)',
              "baseline_ct",
              'EMVI from CT — "positive" or "negative"'),
    ColumnDef("baseline_ct_M",
              'Baseline CT: M(h)',
              "baseline_ct",
              'M staging from CT. Infer "0" from "no metastases/no distant disease/no liver metastases". Infer "1" from "metastases/liver lesions/lung metastases"'),
    ColumnDef("baseline_ct_incidental_yn",
              'Baseline CT: Incidental findings requiring follow up? Y/N(h)',
              "baseline_ct",
              '"Y" if incidental findings mentioned, "N" if explicitly stated none, else empty'),
    ColumnDef("baseline_ct_incidental_detail",
              'Baseline CT: Detail incidental finding(h)',
              "baseline_ct",
              "Description of incidental findings if any"),

    # ── 1ST MDT (cols 27-28) ──
    ColumnDef("first_mdt_date",
              '1st MDT: date(i)',
              "first_mdt",
              "Date of this MDT meeting (DD/MM/YYYY) — from meeting header paragraph"),
    ColumnDef("first_mdt_treatment_approach",
              '1st MDT: Treatment approach \n(TNT, downstaging chemotherapy, downstaging nCRT, downstaging shortcourse RT, Papillon +/- EBRT, straight to surgery(h)',
              "first_mdt",
              'Classify the MDT decision into one of: "TNT", "downstaging chemotherapy", "downstaging nCRT", "downstaging shortcourse RT", "Papillon +/- EBRT", "straight to surgery". Keywords: FOXTROT/CAPOX/FOLFOX→chemotherapy, CRT/chemoradiotherapy/long course→nCRT, short course/SCPRT/5x5→shortcourse RT, Papillon/EBRT→Papillon, surgery/hemicolectomy/resection/surgical review→surgery. Return empty if unclear or treatment approach not yet decided.'),

    # ── CHEMOTHERAPY (cols 29-33) ──
    ColumnDef("chemo_goal",
              'Chemotherapy: Treatment goals  \n(curative, palliative)',
              "chemotherapy",
              '"curative" or "palliative" if stated'),
    ColumnDef("chemo_drugs",
              'Chemotherapy: Drugs',
              "chemotherapy",
              "Drug names if mentioned (e.g. FOLFOX, CAPOX, capecitabine)"),
    ColumnDef("chemo_cycles",
              'Chemotherapy: Cycles',
              "chemotherapy",
              "Number of chemotherapy cycles if mentioned"),
    ColumnDef("chemo_dates",
              'Chemotherapy: Dates',
              "chemotherapy",
              "Chemotherapy dates if mentioned"),
    ColumnDef("chemo_breaks",
              'Chemotherapy: Breaks',
              "chemotherapy",
              "Any treatment breaks mentioned"),

    # ── IMMUNOTHERAPY (cols 34-35) ──
    ColumnDef("immunotherapy_dates",
              'Immunotherapy: Dates',
              "immunotherapy",
              "Immunotherapy dates if mentioned"),
    ColumnDef("immunotherapy",
              'Immunotherapy',
              "immunotherapy",
              "Immunotherapy drug/regimen if mentioned"),

    # ── RADIOTHERAPY (cols 36-39) ──
    ColumnDef("rt_total_dose",
              'Radiotheapy: Total dose',
              "radiotherapy",
              "Total radiotherapy dose if mentioned"),
    ColumnDef("rt_boost",
              'Radiotheapy: Boost',
              "radiotherapy",
              "Radiotherapy boost details if mentioned"),
    ColumnDef("rt_dates",
              'Radiotherapy: Dates',
              "radiotherapy",
              "Radiotherapy dates if mentioned"),
    ColumnDef("rt_concomitant_chemo",
              'Radiotheapy: Concomittant chemotherapy ',
              "radiotherapy",
              "Concomitant chemotherapy with radiotherapy if mentioned"),

    # ── CEA (cols 40-43) ──
    ColumnDef("cea_date",
              'CEA: Date',
              "cea",
              "Date of CEA blood test if mentioned"),
    ColumnDef("cea_value",
              'CEA: Value',
              "cea",
              "CEA value if mentioned"),
    ColumnDef("cea_dre_date",
              'CEA: DRE date ',
              "cea",
              "Date of digital rectal examination if mentioned"),
    ColumnDef("cea_dre_finding",
              'CEA: DRE finding',
              "cea",
              "DRE finding/result if mentioned"),

    # ── SURGERY (cols 44-46) ──
    ColumnDef("surgery_defunctioned",
              'Surgery: Defunctioned?',
              "surgery",
              '"Y" or "N" if defunctioning stoma mentioned'),
    ColumnDef("surgery_date",
              'Surgery: Date of surgery ',
              "surgery",
              "Date of surgery if mentioned"),
    ColumnDef("surgery_intent",
              'Surgery: Intent, pre-neoadjuvant therapy',
              "surgery",
              "Surgical intent if mentioned (e.g. curative, palliative, pre-neoadjuvant)"),

    # ── 2ND MRI (cols 47-54) ──
    ColumnDef("second_mri_date",
              '2nd MRI: Date',
              "second_mri",
              "Date of second/follow-up MRI if mentioned"),
    ColumnDef("second_mri_pathway_status",
              '2nd MRI: Patient pathway status',
              "second_mri",
              "Patient pathway status at 2nd MRI if mentioned"),
    ColumnDef("second_mri_mrT",
              '2nd MRI: mrT',
              "second_mri",
              "T staging from 2nd MRI"),
    ColumnDef("second_mri_mrN",
              '2nd MRI: mrN',
              "second_mri",
              "N staging from 2nd MRI"),
    ColumnDef("second_mri_mrEMVI",
              '2nd MRI: mrEMVI',
              "second_mri",
              'EMVI from 2nd MRI — "positive" or "negative"'),
    ColumnDef("second_mri_mrCRM",
              '2nd MRI: mrCRM',
              "second_mri",
              'CRM from 2nd MRI — "clear", "involved", or "threatened"'),
    ColumnDef("second_mri_mrPSW",
              '2nd MRI: mrPSW',
              "second_mri",
              "PSW from 2nd MRI"),
    ColumnDef("second_mri_trg",
              '2nd MRI: mrTRG score ',
              "second_mri",
              "TRG score from 2nd MRI (1-5 scale)"),

    # ── MDT AFTER 6 WEEKS (cols 55-56) ──
    ColumnDef("mdt_6wk_date",
              'MDT (after 6 week: Date',
              "mdt_6wk",
              "Date of 6-week follow-up MDT if mentioned"),
    ColumnDef("mdt_6wk_decision",
              'MDT (after 6 week: Decision ',
              "mdt_6wk",
              "MDT decision at 6-week follow-up"),

    # ── 12 WEEK MRI (cols 57-63) ──
    ColumnDef("mri_12wk_date",
              '12 week MRI: Date',
              "mri_12wk",
              "Date of 12-week MRI if mentioned"),
    ColumnDef("mri_12wk_mrT",
              '12 week MRI: mrT',
              "mri_12wk",
              "T staging from 12-week MRI"),
    ColumnDef("mri_12wk_mrN",
              '12 week MRI: mrN',
              "mri_12wk",
              "N staging from 12-week MRI"),
    ColumnDef("mri_12wk_mrEMVI",
              '12 week MRI: mrEMVI',
              "mri_12wk",
              'EMVI from 12-week MRI — "positive" or "negative"'),
    ColumnDef("mri_12wk_mrCRM",
              '12 week MRI: mrCRM',
              "mri_12wk",
              'CRM from 12-week MRI — "clear", "involved", or "threatened"'),
    ColumnDef("mri_12wk_mrPSW",
              '12 week MRI: mrPSW',
              "mri_12wk",
              "PSW from 12-week MRI"),
    ColumnDef("mri_12wk_trg",
              '12 week MRI: mrTRG score ',
              "mri_12wk",
              "TRG score from 12-week MRI (1-5 scale)"),

    # ── FLEX SIG FOLLOW-UP (cols 64-65) ──
    ColumnDef("flex_sig_date",
              'Flex sig: Date',
              "flex_sig",
              "Date of follow-up flexible sigmoidoscopy"),
    ColumnDef("flex_sig_findings",
              'Flex sig: Fidnings ',
              "flex_sig",
              "Findings from follow-up flexible sigmoidoscopy"),

    # ── MDT AFTER 12 WEEKS (cols 66-67) ──
    ColumnDef("mdt_12wk_date",
              'MDT (after 12 week): Date',
              "mdt_12wk",
              "Date of 12-week follow-up MDT"),
    ColumnDef("mdt_12wk_decision",
              'MDT (after 12 week): Decision ',
              "mdt_12wk",
              "MDT decision at 12-week follow-up"),

    # ── WATCH AND WAIT (cols 68-73) ──
    ColumnDef("ww_entry_date",
              'Watch and wait: Entered watch + wait, date of MDT ?',
              "watch_and_wait",
              "Date patient entered watch and wait programme"),
    ColumnDef("ww_intent",
              'Watch and wait: Why did they enter wait (with what intent)',
              "watch_and_wait",
              "Reason/intent for entering watch and wait"),
    ColumnDef("ww_frequency",
              'Watch and wait: Frequency?',
              "watch_and_wait",
              "Follow-up frequency for watch and wait"),
    ColumnDef("ww_progression_date",
              'Watch and wait: Date of \nprogression',
              "watch_and_wait",
              "Date of disease progression if mentioned"),
    ColumnDef("ww_progression_site",
              'Watch and wait: Site of \nprogression',
              "watch_and_wait",
              "Site of disease progression if mentioned"),
    ColumnDef("ww_death_date",
              'Watch and wait: Date of death',
              "watch_and_wait",
              "Date of death if mentioned"),

    # ── MRI/FLEXISIG WATCH AND WAIT TRACKING (cols 74-88) ──
    ColumnDef("ww_date_entered",
              'MRI and flexisigmoidoscopy watch and wait dates: Date entered watch and wait',
              "ww_tracking",
              "Date entered watch and wait programme"),
    ColumnDef("ww_flexi_date_1",
              'MRI and flexisigmoidoscopy watch and wait dates: Flexisigmoidoscopy date ',
              "ww_tracking",
              "1st flexisigmoidoscopy date in watch and wait"),
    ColumnDef("ww_flexi_due_1",
              'MRI and flexisigmoidoscopy watch and wait dates: Due date next ',
              "ww_tracking",
              "Due date for next appointment after 1st flexisig"),
    ColumnDef("ww_flexi_date_2",
              'MRI and flexisigmoidoscopy watch and wait dates: Flexisigmoidoscopy date',
              "ww_tracking",
              "2nd flexisigmoidoscopy date"),
    ColumnDef("ww_flexi_due_2",
              'MRI and flexisigmoidoscopy watch and wait dates: Due date next ',
              "ww_tracking",
              "Due date for next appointment after 2nd flexisig"),
    ColumnDef("ww_flexi_date_3",
              'MRI and flexisigmoidoscopy watch and wait dates: Flexisigmoidoscopy date',
              "ww_tracking",
              "3rd flexisigmoidoscopy date"),
    ColumnDef("ww_flexi_due_3",
              'MRI and flexisigmoidoscopy watch and wait dates: Due date next ',
              "ww_tracking",
              "Due date for next appointment after 3rd flexisig"),
    ColumnDef("ww_flexi_date_4",
              'MRI and flexisigmoidoscopy watch and wait dates: Flexisigmoidoscopy date',
              "ww_tracking",
              "4th flexisigmoidoscopy date"),
    ColumnDef("ww_flexi_due_4",
              'MRI and flexisigmoidoscopy watch and wait dates: Due date next ',
              "ww_tracking",
              "Due date for next appointment after 4th flexisig"),
    ColumnDef("ww_mri_date_1",
              'MRI and flexisigmoidoscopy watch and wait dates: MRI Date',
              "ww_tracking",
              "1st MRI date in watch and wait"),
    ColumnDef("ww_mri_due_1",
              'MRI and flexisigmoidoscopy watch and wait dates: Due date next ',
              "ww_tracking",
              "Due date for next appointment after 1st MRI"),
    ColumnDef("ww_mri_date_2",
              'MRI and flexisigmoidoscopy watch and wait dates: MRI Date',
              "ww_tracking",
              "2nd MRI date in watch and wait"),
    ColumnDef("ww_mri_due_2",
              'MRI and flexisigmoidoscopy watch and wait dates: Due date next ',
              "ww_tracking",
              "Due date for next appointment after 2nd MRI"),
    ColumnDef("ww_mri_date_3",
              'MRI and flexisigmoidoscopy watch and wait dates: MRI Date',
              "ww_tracking",
              "3rd MRI date in watch and wait"),
    ColumnDef("ww_mri_due_3",
              'MRI and flexisigmoidoscopy watch and wait dates: Due date next ',
              "ww_tracking",
              "Due date for next appointment after 3rd MRI"),
]

# ── Derived lookups ──

HEADERS: list[str] = [c.header for c in COLUMNS]

KEY_TO_HEADER: dict[str, str] = {c.key: c.header for c in COLUMNS}
HEADER_TO_KEY: dict[str, str] = {c.header: c.key for c in COLUMNS}

FIELD_GROUPS: dict[str, list[ColumnDef]] = {}
for _col in COLUMNS:
    FIELD_GROUPS.setdefault(_col.group, []).append(_col)
